### PR TITLE
Requesting an addition to the comic line

### PR DESCRIPTION
**Pull request by Tofutush**
Hi! I just found about this webring today and it looks nice, especially that subway map! I'd like to add my comic to the map if that's ok!

### CODE REVIEW

**Comment by GusBusDraws** [comment]
Hi @Tofutush! You're welcome to join the comics line! Please add the following HTML to your site to put the widget on one of your pages (I can also give you an extra line of code if you'd like the widget to be on multiple pages) & I'll accept this merge request once I see that the widget is there.

```html
<script src="https://gusbus.space/smallweb-subway.js/comics.js"></script>
<smallweb-subway-comics></smallweb-subway-comics>
```

**Comment by Tofutush** [comment]
Thanks! I've already added the widget by the time I submitted the PR; it's on this page: https://tofutush.github.io/The-Iron-Ragdoll/about

**Comment by GusBusDraws** [comment]
Oh I must have missed that! Perfect! I'll get you on the map!

**Comment by GusBusDraws** [comment]
Here is your stop! Let me know if you'd like me to change the owner field.
image

**Pull request merged**
